# Conversation Manager Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversation-manager
  namespace: qa-agent
  labels:
    app: conversation-manager
    component: communication
    tier: interface
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversation-manager
  template:
    metadata:
      labels:
        app: conversation-manager
        component: communication
        tier: interface
    spec:
      containers:
      - name: conversation
        image: qa-agent/conversation:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: websocket
        - containerPort: 8081
          name: http
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        env:
        - name: AGENT_MODE
          value: "conversation"
        - name: WEBSOCKET_MAX_CONNECTIONS
          value: "1000"
        - name: CONVERSATION_PERSISTENCE
          value: "redis"
        - name: REAL_TIME_ANALYTICS
          value: "enabled"
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: agent-config
              key: redis-url
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: conversation-manager
  namespace: qa-agent
spec:
  selector:
    app: conversation-manager
  ports:
  - name: websocket
    port: 8080
    targetPort: 8080
  - name: http
    port: 8081
    targetPort: 8081
  type: LoadBalancer
